spring:
  datasource:
    url: jdbc:postgresql://userdb.cntzhhzh52ez.eu-central-1.rds.amazonaws.com:5432/userdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: 'none'
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: public
    open-in-view: false
    database: postgresql
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml